### ISSUE TITLE
Binary won't run (cannot load such file -- bundler/setup)

### ISSUE THREAD

**Issue by dhensby** [sminnee/yamlclean#2]
Running on Ubuntu 14.04, Ruby 1.9.3, Gem 1.8.23.

Output received:

```
# yamlclean
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/yamlclean-0.1.2/bin/yamlclean:3:in `<top (required)>'
        from /usr/local/bin/yamlclean:23:in `load'
        from /usr/local/bin/yamlclean:23:in `<main>'
```

**Comment by dhensby** [comment]
OK - looks like bundler is required. I ran `gem install bundler` and then yamlclean works.

This should either not be a dep or should be installed automatically?
